<a href="https://colab.research.google.com/github/saik71234-arch/Python-Data/blob/main/Saikesav_2nd_Month.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 16.08.2025

# **Contact Manager System**

Functions

In [ ]:
grades= [85,90,87,76,99,88]

print(len(grades))

6


In [ ]:
def greet_user():
  print('hello! welcome to our website')

In [ ]:
def add(a,b):
 return a+b

In [ ]:
file=open('example.txt' , 'w')

# Homework- 16.08.2025

'''Create a function named convert_to_fahrenheit. This function should take one argument, a temperature in Celsius, and then convert that temperature to Fahrenheit using a formula. Finally, it should return the Fahrenheit temperature.

Background: The formula to convert Celsius to Fahrenheit is: Fahrenheit = Celsius x 9/5 + 32

Steps

Define a function called convert_to_fahrenheit.
The function should accept one input parameter, celsius, representing a temperature in Celsius.
Inside the function, use the conversion formula to calculate the Fahrenheit equivalent of celsius.
Return the resulting Fahrenheit temperature.'''


In [ ]:
def convert_to_fahrenheit(celsius):
  fahrenheit= celsius*9/5+32
  return fahrenheit
print(convert_to_fahrenheit(25))

77.0


'''Define a function generate_greeting that accepts a name and age, and returns a formatted greeting string

Steps

Define the Function: Start by creating a function named generate_greeting.
Parameters: The function should accept two parameters:
-- name: a string representing the person’s name.

-- age: a number (integer or float) representing the person’s age.

Create the Greeting Message: Inside the function, create a greeting message using these parameters. Use Python’s formatted string (f-string) to insert name and age directly into the message.
Return the Message: Have the function return the greeting message'''



In [ ]:
def generate_greeting(name,age):
  greeting= (f'helo {name} , you are {age} old. ')
  return greeting
print(generate_greeting('saikesav',25))

helo saikesav , you are 25 old. 


'''Write a function named is_even that checks if a given number is even.

Steps

Define the Function: Create a function called is_even.
Parameter: The function will take one parameter:
number: an integer that you want to check.
Determine Evenness: Use the modulo operator % to check if number is divisible by 2. If number % 2 equals 0, the number is even; otherwise, it is odd.
Return Result: If the number is even, the function should return True; if it’s odd, return False.'''


In [ ]:
def is_even(number):
 if number % 2 == 0:
  print('even')
  return True
 else:
  print('odd')
  return False
print(is_even(15))

odd
False


'''Create a file named data.txt using the with statement, and write the text "Python is amazing!" to it.
After writing to the file, read and display the content of data.txt to confirm that the text was successfully written.'''


In [ ]:
file= open('data.txt' , 'w')
file.write('python is amazing!')
file.close()

file= open('data.txt', 'r')
content= file.read()
print(content)
file.close()

python is amazing!


'''Using the with statement, open data.txt and append the text "Let's learn together." to it. After appending, read and display the file’s content to confirm the addition.

Expected Output:

Python is amazing!

Let's learn together.'''

In [ ]:
file= open('data.txt', 'a')
file.write('lets learn together')
file.close()

file= open('data.txt', 'r')
content=file.read()
print(content)
file.close()

python is amazing!lets learn together


'''Create a New File and Write to It Without Using the with Statement Write a program that:

Creates a new file named greetings.txt
Writes the message "Hello, this is a new file!" to the file.
Closes the file after writing.
Reopens the file to read its content and display the message written in the file.
Finally, close the file after reading.'''


In [ ]:
file= open('greetings.txt', 'w')

file.write('Hello,this is a new file!')

file.close()

file= open('greetings.txt', 'r')

content= file.read()

print(content)

file.close()

Hello,this is a new file!


'''To append three new lines to the same greetings.txt file, we can use the 'a' (append) mode in Python.

Expected Output:

After running the code, the content of the greetings.txt file will be:

Content of the greetings.txt file:

Hello, this is a new file!

Hello, User! We're glad to have you here.

Reminder: Don't forget to check your notifications.

Thank you for using our service! Have a great day.'''

In [ ]:
file= open('greetings.txt','a')
file.write("Hello, User! We're glad to have you here.\n")
file.write("Reminder: Don't forget to check your notifications.\n")
file.write("Thank you for using our service! Have a great day.\n")
file.close()

file= open('greetings.txt' ,'r')
content= file.read()
print(content)
file.close()

Hello,this is a new file!Hello, User! We're glad to have you here.
Reminder: Don't forget to check your notifications.
Thank you for using our service! Have a great day.Hello, User! We're glad to have you here.
Reminder: Don't forget to check your notifications.
Thank you for using our service! Have a great day.Hello, User! We're glad to have you here.
Reminder: Don't forget to check your notifications.
Thank you for using our service! Have a great day.Hello, User! We're glad to have you here.
Reminder: Don't forget to check your notifications.
Thank you for using our service! Have a great day.Hello, User! We're glad to have you here.
Reminder: Don't forget to check your notifications.
Thank you for using our service! Have a great day.Hello, User! We're glad to have you here.
Reminder: Don't forget to check your notifications.
Thank you for using our service! Have a great day.
Hello, User! We're glad to have you here.
Reminder: Don't forget to check your notifications.
Thank you for us

'''Multiply Two Numbers Problem: Create a function multiply_numbers that accepts two numbers as arguments and returns their product.

The function should take two numbers (either integers or floats) as input. The function should multiply these two numbers and return the result.

Expected Output:

For the input (4, 5):

20'''

In [ ]:
def multiply_numbers(num1,num2):
 numbers= num1*num2
 return num1*num2
print(multiply_numbers(4,5))

20


'''Create a function reverse_string that accepts a string and returns its reversed version using [::-1].

Expected Output:

For the input "hello":

olleh'''


In [ ]:
def reverse_string(string):
  return string[::-1]
print(reverse_string('hello'))

olleh


'''.Function to Check if a Number is Positive Problem Statement: Create a function is_positive that accepts a number and returns True if the number is positive using comparision operator > otherwise returns False

Expected Output:

For the input 5:

True'''

In [ ]:
def is_positive(number):
  if number >0:
    return True
  else:
    return False
print(is_positive(5))

True


# 17.08.2025

In [ ]:
file= open('example.txt','r')
content= file.read()
print(content)

file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'example.txt'

In [ ]:
line= 'This is the line used in the middle.\n'

with open('example.txt','r')
  lines= file.readlines()

SyntaxError: expected ':' (ipython-input-2039236939.py, line 3)

In [ ]:
with open('example.txt','r') as file:
  file.write('hiii')
  file.seek(0)
  content=file.read()
  print(content)

# .csv

In [ ]:
import csv

with open('marks.csv',mode='r') as file:
  reader = csv.reader(file)
  for row in reader:
    print(row)

['\ufeffSr. No.', 'College', 'Class', 'Exam_id', 'Name', 'Marks']
['1', 'St.Mary', 'BE', '71522622D', 'HOSHING GAUTAM', '420']
['2', 'St.Mary', '', '71522620H', 'GUPTA ABHISHEK', '280']
['3', 'St.Mary', 'BE', '71522628C', 'KALE SHWETA', '350']
['4', 'St.Mary', 'BE', '71522647K', 'AISHWARYA SAWANT', '269']
['5', 'St.Mary', 'BE', '71431647E', 'BENDALE SAGAR SARJERAO', '317']
['6', 'St.Mary', 'BE', '71431650E', 'BHAKTI DUDHANE', '470']
['7', 'St.Mary', 'BE', '71431671H', 'BHOSALE SANGITA BABASAHEB', '333']
['8', 'St.Mary', 'BE', '71522644E', 'RAMIJ TAMBOLI', '365']
['9', 'St.Mary', 'BE', '71431683M', 'CHANDKOTE SEETA DHARMA', '305']
['10', 'St.Mary', 'BE', '71522615M', 'ANIL SUDAM DAKE', '']
['11', 'St.Mary', 'BE', '71522632M', 'NIRAJ MAHAJAN', '460']
['12', 'St.Mary', 'BE', '71522645C', 'SIDDHI PRAVIN RAUT', '474']
['13', 'St.Mary', 'BE', '71431712J', 'DANGAT YOGESH BALASO', '409']
['14', 'St.Mary', 'BE', '71431719F', 'DESAI SHUBHAM HANUMANT', '377']
['15', '', 'BE', '71522612G', 'BORSE 

In [ ]:
import csv

data = [['Name','age','city'],
        ['sai','25','chennai'],
        ['sneha','25','chennai']]

with open('output.csv',mode='w',newline='') as file:
  writer= csv.writer(file)
  writer.writerows(data)

In [ ]:
import csv

new= ['sudha',26,'chennai']

with open('output.csv',mode='a',newline='') as file:
  writer= csv.writer(file)
  writer.writerow(new)

In [ ]:
import csv

with open('output.csv',mode='r') as file:
  reader = csv.reader(file)
  for row in reader:
    print(row)

['Name', 'age', 'city']
['sai', '25', 'chennai']
['sneha', '25', 'chennai']


# HW- 18.08.2025

In [ ]:
def square(x):
 return x**2
print(square(5))


25


In [ ]:
def add(a,b):
  return a+b

print(add(5,6))

11


In [ ]:
def multiply(a,b,c):
  return a*b*c
print(multiply(2,3,4))

24


In [ ]:
def divide(a,b,c,d):
  return(a/(b+c+d))
print(divide(20,2,3,4))

2.2222222222222223


In [ ]:
file= open('user_activity.txt', 'w')

file.write('User logged in at 09:00 AM\n')
file.write('User viewed product details at 09:15 AM\n')
file.write('User added item to cart at 09:30 AM\n')
file.write('User logged out at 10:00 AM\n')

file.close()

file= open('user_activity.txt', 'r')

content= file.read()

print('content of the user_activity.txt file:')
print(content)

file.close()

content of the user_activity.txt file:
User logged in at 09:00 AM
User viewed product details at 09:15 AM
User added item to cart at 09:30 AM
User logged out at 10:00 AM



In [ ]:
file= open('user_activity.txt', 'a')

file.write('User added item to wishlist at 10.30 AM\n')

file.close()

file = open('user_activity.txt', 'r')

content = file.read()

print('Content after appending new data:')
print(content)

file.close()

Content after appending new data:
User logged in at 09:00 AM
User viewed product details at 09:15 AM
User added item to cart at 09:30 AM
User logged out at 10:00 AM
User logged in at 11:00 AM
User added item to wishlist at 10.30 AM
User added item to wishlist at 10.30 AM
User added item to wishlist at 10.30 AM



In [ ]:
with open('user_activity.txt', 'r') as file:
  lines= file.readlines()

specific_line= lines[1]
print(specific_line)

User viewed product details at 09:15 AM



In [ ]:
with open('user_activity.txt', 'r') as file:
  lines= file.readlines()

removed_lines= lines.pop(2)

with open('user_activity.txt', 'w') as modified_file:
    modified_file.writelines(lines)

with open('user_activity.txt', 'r') as modified_file:
    content= modified_file.read()
    print(content)

IndexError: pop index out of range

Problem 9 : Create and Write to a CSV File with User Data Problem Statement: Create a CSV file called users.csv that contains a list of users. Each user has a name, age, and email. Write this information to the CSV file using with statement.

Expected Output:

CSV file content:

John Doe,28,john.doe@example.com

Jane Smith,34,jane.smith@example.com

Bob Johnson,45,bob.johnson@example.com

In [ ]:
import csv

with open('users.csv', mode='w',newline='') as file:
  writer = csv.writer(file)
  writer.writerow(['John Doe',28,'john.doe@example.com'])
  writer.writerow(['Jane Smith',34,'jane.smith@example.com'])
  writer.writerow(['Bob Johnson',45,'bob.johnson@example.com'])

with open('users.csv', mode='r') as file:
  print('csv file content: ')
  print(file.read())

csv file content: 
John Doe,28,john.doe@example.com
Jane Smith,34,jane.smith@example.com
Bob Johnson,45,bob.johnson@example.com



Problem 10 : Append a New User to the CSV File Problem Statement: Append a new user's data (name, age, email) to the existing users.csv file and Display the updated content of the CSV file use with statement.

Expected Output:

Updated CSV file content:

John Doe,28,john.doe@example.com

Jane Smith,34,jane.smith@example.com

Bob Johnson,45,bob.johnson@example.com

Alice Green,29,alice.green@example.com

In [ ]:
import csv

with open('users.csv', mode= 'a', newline= '') as file:
  writer= csv.writer(file)
  writer.writerow(['Alice Green',29,'alice.green@example.com'])

with open('users.csv', mode= 'r') as file:
  print('updated csv file content: ')
  print(file.read())

updated csv file content: 
John Doe,28,john.doe@example.com
Jane Smith,34,jane.smith@example.com
Bob Johnson,45,bob.johnson@example.com
Alice Green,29,alice.green@example.com



Problem 11 : Delete a Row by Index from the CSV File Problem Statement: Delete a user by index (e.g., the second user, "Jane Smith") from the users.csv file. Write the updated content back to the CSV file Display the updated CSV file content use with statement.

Expected Output:

Updated CSV file content after deletion:

John Doe,28,john.doe@example.com

Jane Smith,34,jane.smith@example.com

Alice Green,29,alice.green@example.com

In [ ]:
import csv

with open ('users.csv',mode='r') as file:
 rows= list(csv.reader(file))

del rows[2]

with open('users.csv',mode='w',newline='') as file:
  writer= csv.writer(file)
  writer.writerows(rows)

with open('users.csv',mode='r') as file:
  print('updated csv file content after deletion: ')
  print(file.read())

updated csv file content after deletion: 
John Doe,28,john.doe@example.com
Jane Smith,34,jane.smith@example.com
Alice Green,29,alice.green@example.com



Problem 12: Read Specific User Data by Index from the CSV File Problem Statement: Read and display the information of a specific user (e.g., the second user, "Jane Smith") from the users.csv file by using the index and with statement.

Expected Output:

Specific user at index 3: ['Bob Johnson', '45', 'bob.johnson@example.com']

In [ ]:
import csv

with open('users.csv',mode='r')as file:
 rows= list(csv.reader(file))

third_user= rows[2]

print('specific user at index 3: ')
print(third_user)

specific user at index 3: 
['Alice Green', '29', 'alice.green@example.com']


30.08.2025

# LAMBDA FUNCTION

In [ ]:
def double(x)
 return x*2
 print(double(5))

In [ ]:
double= lambda x: x*2
print(double(4))

8


In [ ]:
square= lambda x: x**2
print(square(2))

4


In [ ]:
format_name= lambda first_name, last_name: f'{first_name} {last_name}'
print(format_name('sai','kesav'))


sai kesav


In [ ]:
total= lambda maths,science,english: maths+science+english
print(total(50,60,70))

180


In [ ]:
classify= lambda x: 'positive' if x>0 else 'Negative'
print(classify(5))

positive


In [ ]:
even_or_odd= lambda x: 'even' if x%2==0 else 'odd'
print(even_or_odd(5))

odd


In [ ]:
numbers= [1,2,3,4]
double= map(lambda x: x*2,numbers)
print(list(double))

[2, 4, 6, 8]


In [ ]:
list1= ['sai','sneha','keerthana']
list2= ['kesav','krishnan','murali']

combined= map(lambda x,y: x+' '+y,list1,list2)
print(list(combined))

['sai kesav', 'sneha krishnan', 'keerthana murali']


In [ ]:
titles= ('Mr','Ms','Mr')
names= ('sai','sneha','guru')
full_names= tuple(map(lambda x,y:x+" "+y,titles,names))
print(full_names)

('Mr sai', 'Ms sneha', 'Mr guru')


In [ ]:
marks= [25,65,75,90]
pass_mark= filter(lambda x: x>=50,marks)
print(list(pass_mark))

[65, 75, 90]


In [ ]:
customer_spending=[75,120,140,90,110]
high_spenders= filter(lambda x:x>=100,customer_spending)
print(list(high_spenders))

[120, 140, 110]


In [ ]:
employee= ['sai','kumar','rohit']
salaries=[20,50,60]
experience=[1,2,3]

eligible_employees= filter(
    lambda i: salaries[i]>50 and experience[i]>2,
    range(len(employee))
)
result= [employee[i] for i in eligible_employees]
print(result)


['rohit']


# 30-08-2025

1.Problem Statement: Write a lambda function that takes two numbers and returns their sum.

Expected Output: 7


In [ ]:
sum= lambda x,y: x+y
print(sum(2,5))

7


2.Problem Statement: Write a lambda function that takes two numbers and returns the larger number.

Expected Output: 10

In [ ]:
largest_number= lambda x,y : x if x>y else y
print(largest_number(5,10))

10


3.Problem Statement: Write a lambda function that takes three parameters and returns their average.

Expected Output: 6.0

In [ ]:
average = lambda x,y,z:(x+y+z)/3
print(average(1,2,3))

2.0


4.Problem Statement: Write a lambda function to check if a given string is a palindrome. The lambda function should return True if the string is the same when read forwards and backwards, and False otherwise.

**Expected Output:**If the string is a palindrome, the output should be True, otherwise False.

In [ ]:
palindrome= lambda x: True if x[::-1]==x else False
print(palindrome("MalayalaM"))

True


5.Problem Statement: Write a lambda function that takes a string as input and returns the length of the string.

Expected Output: The output should be the integer value representing the length of the input string.

Example: Input: "hello" Output: 5

Input: "python" Output: 6

In [ ]:
length= lambda x:len(x)
print(length('hello'))

5


6.Problem Statement:**Write a lambda function that takes a number as input and checks if it is divisible by both 2 and 3. The function should return True if the number is divisible by both, otherwise return False.

Expected Output: The output should be True if the number is divisible by both 2 and 3, otherwise False.

Example:

Input: 6

Output: True

In [ ]:
number= lambda x:x%2==0 and x%3==0
print(number(6))

True


7.Problem Statement: Write a program that uses the map() function along with a lambda function to multiply each element in the given list by 2. The output should be a new list with each element multiplied by 2.

Expected Output: The output should be a list where each number is multiplied by 2.

Example:

Input: [1, 2, 3, 4, 5]

Output: [2, 4, 6, 8, 10]

In [ ]:
value = [1,2,3,4,5]
double= map(lambda x: x*2,value)
print(list(double))

8.Problem Statement: Write a program that uses the map() function along with a lambda function to return the length of each word in the given list of words. The output should be a list containing the length of each word.

Expected Output: The output should be a list of integers where each element is the length of the corresponding word in the input list.

Example:

Input: ["apple", "banana", "cat"]

Output: [5, 6, 3]

In [ ]:
fruits=['apple','banana','cat']
word_lengths= map(lambda a:len(a),fruits)
print(list(word_lengths))

9.Problem Statement: Write a program that uses the map() function along with a lambda function to convert a list of strings to integers. The output should be a list containing the integer representation of each string in the input list.

Expected Output: The output should be a list of integers corresponding to each string in the input list.

Example:

Input: ["1", "2", "3", "4"]

Output: [1, 2, 3, 4]

In [ ]:
input= ['1','2','3','4']
integer= map(lambda x:int(x),input)
print(list(integer))

10.Problem Statement: Write a Python program that uses the map() function and a lambda function to add corresponding elements from two lists of equal length. The program should return a list of sums where each element is the sum of the corresponding elements from both lists.

Expected Output:The output is a list of sums calculated for each pair of corresponding elements from list1 and list2:

1 + 5 = 6

2 + 6 = 8

3 + 7 = 10

Thus, the program outputs [6, 8, 10].

In [ ]:
a1=[1,2,3]
b1=[5,6,7]
c1= map(lambda x,y:x+y,a1,b1)
print(list(c1))

11.Problem Statement: Write a Python program that uses the map() function and a lambda function to find the product of corresponding elements in two tuples of equal length. The program should return a list where each element is the product of the corresponding elements from both tuples.

Expected Output:The output is a list of products calculated for each pair of corresponding elements from tuple1 and tuple2:

1 * 5 = 5

2 * 6 = 12

3 * 7 = 21

Thus, the program outputs [5, 12, 21]

In [ ]:
a= (1,2,3)
b= (5,6,7)
c= map(lambda x,y:x*y,a,b)
print(list(c))

2.Problem Statement:

Write a Python program using a lambda function to calculate the product of three numbers.

Expected Output: 24

In [ ]:
product= lambda x,y,z:x*y*z
print(product(2,3,4))


24


13.Problem Statement: Write a program using a lambda function to find the minimum of two numbers.

Expected Output:

3

In [ ]:
minimum= lambda x,y:x if x<y else y
print(minimum(3,5))

3


**14.Problem Statement:**Write a Python program using a lambda function to concatenate three strings.

Expected Output:

Hello World Python

Explanation: The lambda function will take three string parameters and return the result of their concatenation.

In [ ]:
combine= lambda x,y,z:x+' '+y+' '+z
print(combine('hello','world','python'))

hello world python


# 31.8.2025- OOPS

In [ ]:
class car:
  def __init__(self,color,model,speed):
    self.color= color
    self.model= model
    self.speed= speed

  def details(self):
    print(f'This is a {self.color}{self.model} with a speed of {self.speed} mph')
  def speed_info(self):
    print(f'The speed of the car is {self.speed}mph')

car1=car('Red','Toyota corolla',100)
car2= car('Blue','Honda civic',120)

car1.details()
car2.details()

car1.speed_info()

This is a RedToyota corolla with a speed of 100 mph
This is a BlueHonda civic with a speed of 120 mph
The speed of the car is 100mph


# **OOPS**

# BANK STATEMENT

In [ ]:
class BankAccount:
  def __init__(self,owner,balance):
    self.owner=owner
    self._balance=balance

  def deposit(self,amount):
    if amount>0:
      self._balance += amount
      print(f"Deposited{amount}.New balance: {self._balance}")
    else:
      print("Invalid deposit amount.Amount must be greater than zero.")

  def withdraw(self,amount):
    if 0 < amount <= self._balance:
      self._balance -= amount
      print(f"Withdraw{amount},Remaining balance:{self._balance}")
    else:
       print("Invalid Withdrawal")

  def get_balance(self):
     return self._balance

account= BankAccount('Saikesav',1000)
account.deposit(500)
account.withdraw(200)
print('Final balance:',account.get_balance())

print(account._balance)

Deposited500.New balance: 1500
Withdraw200,Remaining balance:1300
Final balance: 1300
1300


# **NUMpy**

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
scalar= np.array(5)
print(scalar)

5


In [ ]:
print(scalar.ndim)

0


In [ ]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
print(a.ndim)

1


In [ ]:
menu= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(menu)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


#Shape

In [ ]:
print(menu.ndim)

3


In [ ]:
print(menu.shape)

(1, 3, 4)


In [ ]:
print(menu.size)

12


In [ ]:
print(menu.dtype)

int64


In [ ]:
print(menu.T)

[[[ 1]
  [ 5]
  [ 9]]

 [[ 2]
  [ 6]
  [10]]

 [[ 3]
  [ 7]
  [11]]

 [[ 4]
  [ 8]
  [12]]]


In [ ]:
seats = np.arange(1, 12)
print(seats)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
seats= np.arange(1,10,2)
print(seats)

[1 3 5 7 9]


In [ ]:
score= np.zeros([3,5])
print(score)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
score= np.ones([3,5])
print(score)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a= np.linspace(7,20,48)
print(a)

[ 7.          7.27659574  7.55319149  7.82978723  8.10638298  8.38297872
  8.65957447  8.93617021  9.21276596  9.4893617   9.76595745 10.04255319
 10.31914894 10.59574468 10.87234043 11.14893617 11.42553191 11.70212766
 11.9787234  12.25531915 12.53191489 12.80851064 13.08510638 13.36170213
 13.63829787 13.91489362 14.19148936 14.46808511 14.74468085 15.0212766
 15.29787234 15.57446809 15.85106383 16.12765957 16.40425532 16.68085106
 16.95744681 17.23404255 17.5106383  17.78723404 18.06382979 18.34042553
 18.61702128 18.89361702 19.17021277 19.44680851 19.72340426 20.        ]


In [ ]:
a= (1,2,3,4,5,6)
arrayfromtuple=np.array(a)
print(arrayfromtumple)

NameError: name 'np' is not defined